#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    length = len(arr)
    count_Pos = 0
    count_Ne=0
    count_ze=0
    for i in arr:
        if i > 0:
            count_Pos+=1
        elif i == 0:
            count_ze+=1
        else:
            count_Ne+=1
    print(round(count_Pos/length,6))
    print(round(count_Ne/length,6))
    print(round(count_ze/length,6))
    

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
