#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    meridian = s[-2:]
    if meridian=="PM":
        
        time=int(s[:2])
        if time < 12:
            time+=12
            
        return str(time)+s[2:len(s) - 2]
    else:
        time=int(s[:2])
        if time>12:
            time+=12
            return str(time)+s[2:len(s) - 2]
        elif time == 12:
            
            time=0
            return '0'+str(time)+s[2:len(s) - 2]
        else:
            return '0'+str(time)+s[2:len(s) - 2]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
